# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56277b788249437b35c84396a6ad02cfdcf88d9d0d41cbdb3024ddebed6c82f8e1fcb0e5959316a34a83a0ad7c8aef182f414583cd9dec23f805a04cdb1bf60a

test:
  secret_key_base: b6a58157cb6c5a19058a942dc553ebc53f2fab3cef7d0716afc84ec59f22e75e768be81c30a765471a27fc94814ac8daa3d6979eb4128c9851dd2b634a4a44d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
